### ISSUE TITLE
在Zeabur部署后发起对话时出现“请求处理时发生错误: Error: OpenAI API 请求失败”

### ISSUE THREAD

**Issue by 18502074216** [fatwang2/search2ai#36]
使用不同的代理地址或者默认的openai api都会出现这一情况：

请求处理时发生错误: Error: OpenAI API 请求失败

    at handleRequest (/src/api/search2ai.js:107:15)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async module.exports (/src/api/index.js:87:24)

    at async /src/api/index.js:145:13

Sending response as a string or Buffer

![image](https://github.com/user-attachments/assets/ef6dbba8-c986-4c77-b29a-cbc4ec6c6bbb)
以下是我配置的环境变量
![image](https://github.com/user-attachments/assets/0f7b760b-3610-4562-898a-60f1722eee48)

请问该如何解决？

**Comment by fatwang2** [comment]
你现在发的截图应该是一个代理网站，且用的是moonshot，moonshot格式不完全一样，项目里有个单独的代码文件
